"""
Real AI API Endpoints

This module provides production-ready AI API endpoints that integrate with
Claude Haiku 3.5. Replaces any mock or placeholder AI endpoints.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List, Dict, Any
import logging

from ..database import get_db
from .. import schemas
from ..services.ai_service import ai_service
from ..config.settings import settings


router = APIRouter(prefix="/ai", tags=["AI Services"])


@router.post("/chat", response_model=schemas.AIResponse, summary="AI Chat Assistant")
async def ai_chat(
    request: schemas.AIChatRequest,
    db: Session = Depends(get_db)
):
    """
    Real AI chat endpoint using Claude Haiku 3.5.
    
    This endpoint provides production-ready AI assistance for building materials
    queries. No mock or placeholder responses.
    
    Args:
        request: Chat request with user query and optional context
        db: Database session
        
    Returns:
        AI response with recommendations and analysis
    """
    try:
        # Validate API key is configured
        if not settings.anthropic_api_key:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI szolgáltatás nem elérhető - API kulcs nincs konfigurálva"
            )
        
        logging.info(f"AI chat request: {request.query}")
        
        # Get context products if provided
        context_products = []
        if request.context_product_ids:
            # Fetch products from database
            from ..models import Product
            products = db.query(Product).filter(
                Product.id.in_(request.context_product_ids)
            ).all()
            
            context_products = [
                {
                    "id": p.id,
                    "name": p.name,
                    "description": p.description,
                    "category": p.category.name if p.category else "N/A",
                    "manufacturer": p.manufacturer.name if p.manufacturer else "N/A",
                    "technical_specs": p.technical_specs or {}
                }
                for p in products
            ]
        
        # Generate AI response using real Claude API
        ai_response = await ai_service.get_product_recommendations(
            user_query=request.query,
            context_products=context_products
        )
        
        # Log successful interaction
        logging.info(f"AI response generated for query: {request.query}")
        
        return schemas.AIResponse(
            query=request.query,
            response=ai_response,
            context_products=context_products,
            model_used=settings.ai.model_name,
            timestamp=None  # Will be auto-generated by Pydantic
        )
        
    except Exception as e:
        logging.error(f"AI chat error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Hiba történt az AI válasz generálása során: {str(e)}"
        )


@router.post("/extract-specs", response_model=schemas.SpecExtractionResponse)
async def extract_product_specifications(
    request: schemas.SpecExtractionRequest,
    db: Session = Depends(get_db)
):
    """
    Extract technical specifications from PDF content using real AI.
    
    Args:
        request: PDF content and optional product context
        db: Database session
        
    Returns:
        Extracted specifications in structured format
    """
    try:
        # Validate API key
        if not settings.anthropic_api_key:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI szolgáltatás nem elérhető - API kulcs nincs konfigurálva"
            )
        
        logging.info(f"Spec extraction request for: {request.product_name}")
        
        # Extract specifications using real Claude API
        extracted_specs = await ai_service.extract_product_specifications(
            pdf_content=request.pdf_content,
            product_name=request.product_name or ""
        )
        
        logging.info(f"Specs extracted for: {request.product_name}")
        
        return schemas.SpecExtractionResponse(
            product_name=request.product_name,
            extracted_specs=extracted_specs,
            confidence_score=extracted_specs.get(
                "kinyeresi_metaadatok", {}
            ).get("megbizhatos agi_pontszam", 0.0),
            model_used=settings.ai.model_name
        )
        
    except Exception as e:
        logging.error(f"Spec extraction error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Hiba történt a műszaki adatok kinyerése során: {str(e)}"
        )


@router.post("/analyze-compatibility", response_model=schemas.CompatibilityResponse)
async def analyze_system_compatibility(
    request: schemas.CompatibilityRequest,
    db: Session = Depends(get_db)
):
    """
    Analyze compatibility between building materials using real AI.
    
    Args:
        request: List of product IDs to analyze
        db: Database session
        
    Returns:
        Compatibility analysis results
    """
    try:
        # Validate API key
        if not settings.anthropic_api_key:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="AI szolgáltatás nem elérhető - API kulcs nincs konfigurálva"
            )
        
        logging.info(f"Compatibility analysis for {len(request.product_ids)} products")
        
        # Fetch products from database
        from ..models import Product
        products = db.query(Product).filter(
            Product.id.in_(request.product_ids)
        ).all()
        
        if not products:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Nem található termék a megadott azonosítókkal"
            )
        
        # Prepare product data for AI analysis
        product_data = [
            {
                "id": p.id,
                "name": p.name,
                "category": p.category.name if p.category else "N/A",
                "manufacturer": p.manufacturer.name if p.manufacturer else "N/A",
                "technical_specs": p.technical_specs or {}
            }
            for p in products
        ]
        
        # Analyze compatibility using real Claude API
        compatibility_result = await ai_service.analyze_system_compatibility(product_data)
        
        logging.info(f"Compatibility analysis completed for {len(products)} products")
        
        return schemas.CompatibilityResponse(
            product_ids=request.product_ids,
            compatibility_result=compatibility_result.get("kompatibilitas_eredmeny", "nem_elemezheto"),
            warnings=compatibility_result.get("figyelmeztesek", []),
            recommendations=compatibility_result.get("ajanlasok", []),
            analysis_details=compatibility_result.get("szakmai_indoklas", ""),
            model_used=settings.ai.model_name
        )
        
    except Exception as e:
        logging.error(f"Compatibility analysis error: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Hiba történt a kompatibilitás elemzése során: {str(e)}"
        )


@router.get("/health", summary="AI Service Health Check")
async def ai_health_check():
    """
    Check if AI service is properly configured and accessible.
    
    Returns:
        Health status of AI service
    """
    try:
        api_key_configured = bool(settings.anthropic_api_key)
        
        return {
            "status": "healthy" if api_key_configured else "degraded",
            "model": settings.ai.model_name,
            "provider": settings.ai.provider,
            "api_key_configured": api_key_configured,
            "message": "AI szolgáltatás üzemkész" if api_key_configured else "API kulcs nincs konfigurálva"
        }
        
    except Exception as e:
        logging.error(f"AI health check error: {e}")
        return {
            "status": "unhealthy",
            "model": settings.ai.model_name,
            "provider": settings.ai.provider,
            "api_key_configured": False,
            "message": f"AI szolgáltatás hiba: {str(e)}"
        }